# Generated by Django 4.1.7 on 2023-04-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='in progress', max_length=20)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
